Repository 03-cs-wockys-waywards/capstone, pull requests merged in 2021-07, with the labels that each got.

#26 Profile step 1
  App.js
  package-lock.json
  package.json
  src/components/Checkbox.js
  src/components/ProgressCircles.js
  src/screens/SetUpProfileScreens/ProfileStepOne.js
  src/screens/SetUpProfileScreens/styles.js
Labels: enhancement

#28 Profile pic
  App.js
  package-lock.json
  package.json
  src/screens/AddProfilePic/AddProfilePic.js
  src/screens/AddProfilePic/styles.js
Labels: enhancement

#36 fix(#34): retrieve initial states from redux store if they exist
  package-lock.json
  src/screens/SetUpProfileScreens/ProfileStepOne/ProfileStepOne.js
Labels: bug, improvement

#44 User: Profile Set Up Confirmation Screen
  App.js
  src/components/Pill.js
  src/helpers/displaySemanticPronouns.js
  src/helpers/getRandomLightColor.js
  src/images/default-profile-picture.jpg
  src/screens/RegistrationScreen/RegistrationScreen.js
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
  src/screens/SetUpProfileScreens/Confirmation/styles.js
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
  src/screens/SetUpProfileScreens/confirmationDummy.js
  src/screens/index.js
Labels: enhancement

#50 Upload images
  .gitignore
  App.js
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
Labels: enhancement

#56 Search users
  src/components/SearchBar.js
  src/screens/HomeScreen/UsersList.js
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
Labels: enhancement

#76 Refactor userslist
  App.js
  package-lock.json
  src/Main.js
  src/components/StatusBar.js
  src/screens/HomeScreen/DiscoverList.js
  src/screens/HomeScreen/Home.js
  src/screens/HomeScreen/MatchesList.js
  src/screens/HomeScreen/UserRow.js
  src/screens/HomeScreen/UsersList.js
  src/store/discoverUsersReducer.js
  src/store/index.js
  src/store/potentialMatchesReducer.js
  src/store/userReducer.js
  src/store/usersReducer.js
Labels: enhancement

#85 fix: logout automatically returns to login page
  App.js
  src/screens/ProfileScreen/Header.js
Labels: bug

#90 Flatlist
  src/screens/HomeScreen/DiscoverList.js
  src/screens/HomeScreen/MatchesList.js
  src/screens/HomeScreen/UserRow.js
  src/screens/SingleUserProfileScreen/SingleUserProfile.js
Labels: bug, improvement

#113 Default profile photo
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
  src/screens/SetUpProfileScreens/ProfileStepThree/styles.js
Labels: enhancement

#125 Edit Profile Picture Process
  src/screens/EditProfileScreen/EditProfileScreen.js
  src/screens/EditProfileScreen/UpdateImage/ImageModal.js
  src/screens/EditProfileScreen/UpdateImage/UpdateImage.js
Labels: bug, improvement

#126 Edit Profile Styling
  App.js
  src/components/SmallPill.js
  src/screens/EditProfileScreen/UpdateImage/ImageModal.js
  src/screens/EditProfileScreen/UpdateInterests/InterestsModal.js
  src/screens/EditProfileScreen/UpdateInterests/UpdateInterests.js
  src/screens/EditProfileScreen/UpdatePronouns.js
  src/screens/EditProfileScreen/styles.js
  src/screens/ProfileScreen/styles.js
Labels: improvement, ui/ux

#128 quick fix: fix logout and persist changes from edit profile screen
  package-lock.json
  src/screens/ChatScreens/ChatFeedScreen.js
  src/screens/EditProfileScreen/EditProfileScreen.js
Labels: bug

#134 Tutorial modal
  package-lock.json
  package.json
  src/components/TutorialModal.js
  src/screens/HomeScreen/UsersList.js
  src/screens/HomeScreen/styles.js
  src/screens/LoadScreen/LoadScreen.js
  src/screens/LoadScreen/styles.js
Labels: enhancement

#136 iss(#122): Profile Setup Styling
  App.js
  src/components/Checkbox.js
  src/components/InterestButton.js
  src/components/ProgressCircles.js
  src/screens/EditProfileScreen/styles.js
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
  src/screens/SetUpProfileScreens/Confirmation/styles.js
  src/screens/SetUpProfileScreens/ProfileStepOne/ProfileStepOne.js
  src/screens/SetUpProfileScreens/ProfileStepOne/styles.js
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
  src/screens/SetUpProfileScreens/ProfileStepThree/styles.js
  src/screens/SetUpProfileScreens/ProfileStepTwo/InterestsScreen.js
  src/screens/SetUpProfileScreens/ProfileStepTwo/styles.js
Labels: ui/ux

#138 Cloudinary Setup
  package-lock.json
  package.json
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
Labels: improvement

#146 feat(#145): User can pull to refresh
  src/screens/HomeScreen/DiscoverList.js
  src/screens/HomeScreen/styles.js
  src/store/discoverUsersReducer.js
Labels: enhancement, improvement

#148 Edit profile pic cloudinary
  src/screens/EditProfileScreen/UpdateImage/ImageModal.js
  src/screens/EditProfileScreen/UpdateImage/UpdateImage.js
  src/screens/SetUpProfileScreens/Confirmation/ConfirmationScreen.js
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
Labels: improvement

#151 feat: allow default photo usage when app has no camera/gallery access
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
  src/screens/SetUpProfileScreens/ProfileStepThree/styles.js
Labels: improvement

#154 Changed tapping on User Row
  src/screens/HomeScreen/UserRow.js
  src/screens/HomeScreen/styles.js
Labels: ui/ux

#156 Splash & icon
  App.js
  assets/icon.png
  assets/splash.png
  src/screens/LandingScreen/styles.js
  src/screens/SetUpProfileScreens/Confirmation/styles.js
Labels: bug, ui/ux

#158 Env file
  .babelrc
  App.js
  babel.config.js
  package-lock.json
  package.json
  src/screens/SetUpProfileScreens/ProfileStepThree/AddProfilePic.js
Labels: improvement

#162 Update app.json file to be about Tingle
  app.json
Labels: documentation

#163 Enlarge photo
  src/screens/ProfileScreen/UserDetails.js
  src/screens/ProfileScreen/styles.js
  src/screens/SingleUserProfileScreen/EnlargedImageModal.js
  src/screens/SingleUserProfileScreen/SingleUserProfile.js
  src/screens/SingleUserProfileScreen/styles.js
Labels: enhancement

#166 Matches pull to refresh/Single tap
  package.json
  src/components/Pill.js
  src/components/SearchBar.js
  src/components/SmallPill.js
  src/screens/EditProfileScreen/UpdateInterests/InterestsModal.js
  src/screens/EditProfileScreen/UpdateInterests/UpdateInterests.js
  src/screens/EditProfileScreen/UpdatePronouns.js
  src/screens/EditProfileScreen/styles.js
  src/screens/HomeScreen/DiscoverList.js
  src/screens/HomeScreen/MatchesList.js
  src/screens/HomeScreen/UserRow.js
  src/screens/HomeScreen/UsersList.js
  src/screens/HomeScreen/styles.js
  src/screens/LandingScreen/styles.js
  src/screens/ProfileScreen/styles.js
  src/screens/SearchScreen/SearchScreen.js
  src/screens/SearchScreen/styles.js
  src/screens/SetUpProfileScreens/Confirmation/styles.js
  src/screens/SetUpProfileScreens/ProfileStepTwo/styles.js
  src/screens/SingleUserProfileScreen/SingleUserProfile.js
  src/screens/SingleUserProfileScreen/styles.js
  src/store/discoverUsersReducer.js
  src/store/potentialMatchesReducer.js
Labels: improvement, ui/ux

#167 bottom nav bar icons
  src/Main.js
  src/screens/HomeScreen/Home.js
Labels: ui/ux
